name: EntityManager
author: milkywayz 
main: net.milkycraft.EntityManager
version: 5.4.4
commands:   
    entitymanager:      
      aliases: em      
      description: The main command for entitymanager

  