name: EntityManager
author: milkywayz 
main: net.porillotityManager
version: ${project.version}
commands:   
    entitymanager:      
      aliases: em      
      description: The main command for EntityManager

  